/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#5f4100',
        'on-tertiary-container': '#4d3500',
        'primary': '#a2c9ff',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#2d363e',
        'on-background': '#dae3ee',
        'background': '#0b141c',
        'on-error': '#690005',
        'inverse-primary': '#0060aa',
        'inverse-on-surface': '#29313a',
        'surface-container': '#182028',
        'surface': '#0b141c',
        'tertiary-container': '#d29922',
        'inverse-surface': '#dae3ee',
        'secondary': '#c3c6cf',
        'primary-container': '#58a6ff',
        'surface-variant': '#2d363e',
        'primary-fixed': '#d3e4ff',
        'secondary-fixed': '#dfe2eb',
        'on-primary-container': '#003a6b',
        'surface-tint': '#a2c9ff',
        'secondary-container': '#454950',
        'surface-container-lowest': '#060f16',
        'outline-variant': '#414752',
        'on-surface-variant': '#c0c7d4',
        'tertiary-fixed': '#ffdeaa',
        'primary-fixed-dim': '#a2c9ff',
        'on-secondary': '#2d3137',
        'error-container': '#93000a',
        'surface-bright': '#313a43',
        'surface-dim': '#0b141c',
        'on-surface': '#dae3ee',
        'on-secondary-container': '#b5b8c1',
        'on-secondary-fixed-variant': '#43474e',
        'on-tertiary': '#422c00',
        'on-primary': '#00315c',
        'on-secondary-fixed': '#181c22',
        'on-primary-fixed-variant': '#004882',
        'surface-container-high': '#222b33',
        'tertiary': '#fabc45',
        'on-tertiary-fixed': '#271900',
        'on-primary-fixed': '#001c38',
        'tertiary-fixed-dim': '#fabc45',
        'surface-container-low': '#141c24',
        'error': '#ffb4ab',
        'outline': '#8b919d',
        'secondary-fixed-dim': '#c3c6cf',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        unit: '4px',
        gutter: '16px',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-md': ['IBM Plex Sans'],
        'body-md': ['IBM Plex Sans'],
        'mono-data': ['IBM Plex Mono'],
        'label-md': ['IBM Plex Sans'],
        'display-lg': ['IBM Plex Sans'],
        'body-lg': ['IBM Plex Sans'],
        'headline-lg': ['IBM Plex Sans'],
        'body-sm': ['IBM Plex Sans'],
        'headline-sm': ['IBM Plex Sans'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '450' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
